default_chain: stride-testnet
chains:
  gaia-testnet:
    key: Exodusw
    chain-id: GAIA
    rpc-addr: http://138.2.183.59:23657      
    grpc-addr: http://138.2.183.59:23090    
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: Exodusw
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://144.24.172.197:16657      
    grpc-addr: http://144.24.172.197:16090    
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
